### ISSUE TITLE
Splitting error handling and action creators

### ISSUE THREAD

**Issue by jgzamora** [SparkPost/2web2ui#112]
At some point we will want to chain different actions, while controlling error handling and alerts that come from each action. To do this with an action that has error handling built in, you'd have to re-write the whole action creator. Take `deleteUser` for example:
```javascript
export function deleteUser(username) {
  const action = {
    type: 'DELETE_USER',
    meta: {
      data: { username }, // need in reducer, no user reference in response
      method: 'DELETE',
      url: `/users/${username}`
    }
  };

  return (dispatch) => dispatch(sparkpostApiRequest(action))
    .then(() => dispatch(showAlert({
      type: 'success',
      message: `Successfully deleted ${username}`
    })))
    .catch(() => dispatch(showAlert({
      type: 'error',
      message: `Unable to delete ${username}.`
    })));
}
```
It dispatches alerts on success and fail. If I needed to delete a user as a part of a chain of actions but didn't want to dispatch the alerts, or I wanted to throw an error instead, I would have to write a new action creator. 

Proposed solution: extract the action object and dispatch call from current action creators into separate functions.

`/actions/someFolder/users.js`
```javascript
function deleteUserAction(dispatch, username) {
  const action = {
    type: 'DELETE_USER',
    meta: {
      data: { username }, // need in reducer, no user reference in response
      method: 'DELETE',
      url: `/users/${username}`
    }
  };

  return dispatch(sparkpostApiRequest(action));
}

//this can go anywhere else, just another example
function showAlertAction(dispatch, alert) {
  return dispatch(showAlert(alert));
}
```

`/actions/users.js`
```javascript
import { deleteUserAction,  showAlertAction} from './someFolder/users.js'
export function deleteUser(username) {
  return (dispatch) => deleteUserAction(dispatch, username)
    .then(() => showAlertAction(dispatch, {
      type: 'success',
      message: `Successfully deleted ${username}`
    }))
    .catch(() => showAlertAction(dispatch, {
      type: 'error',
      message: `Unable to delete ${username}.`
    }));
}
```

This way, if I want to delete a user while doing a bunch of other stuff to I can just:
```javascript
// async await cause it looks pretty
export function notJustDeleteUser(username, otherStuff) {
  return async (dispatch) => {
    try {
      const userDelete = await deleteUserAction(dispatch, username);
      return await otherThingAction(otherStuff);
    } catch(error) {
      return showAlertAction(dispatch, {
        type: 'error',
        message: 'VERY DIFFERENT SPECIAL ALERT, I don\'t even have to do this if I don\'t want.'
      );
    }
  }
}
```
And I don't have to re-write the deleteUserAction in order to show my own alert.

The examples are just *an* implementation, I'm sure we can make it better + better looking. I was trying to do this without passing `dispatch` to the basic actions but gave up immediately. I haven't tried the async await version, but other version works in the current app.

**Comment by jonambas** [comment]
So I wanted to keep these at the component level because there are some things that can't or shouldn't be done in the action. ie setState, history.push, form functions, ui stuff.

Tried doing this and the `onCancel` and `reset` still go off with an error. Or am I misunderstanding something?
```js
// action
export function updateBillingContact(data) {
  const action = sparkpostApiRequest(...);

  return (dispatch) => dispatch(action)
    .then(() => dispatch(showAlert({ type: 'success', message: 'Billing Contact Updated' })))
    .catch(() => dispatch(showAlert({ type: 'error', message: 'Billing Contact failed' })));
}

// form
onSubmit = (values) => {
    const { updateBillingContact, onCancel, reset } = this.props;
    return updateBillingContact(values).then(() => {
      // showAlert({ type: 'success', message: 'Billing Contact Updated' });
      onCancel(); // closes modal
      reset(); // resets form
    })
    // .catch((err) => showAlert({ type: 'error', message: 'Billing Contact Update Failed' }));
  }
```

**Comment by jgzamora** [comment]
👍 extracting the error handling to components totally makes sense from that point of view.

I think that we should have error signaling come down from the reducers, as opposed to directly from the action. Setting `.then()` and `.catch()` on the action from the components feels a little bit like circumventing the flow. 

Something like:
* use local state to keep track of updates going to happen (optional)
* set specific error and success cases on reducers
* use a lifecycle method to validate error / success against local state if you had a `toBeUpdated` or `toBeDeleted` from the first bullet (optional)
* use lifecycle method or render to `showAlert`, redirect, or anything else
* allowed to use `.then()` on action, but works more like a `.finally()` or `.always()`

I'll get a dmo of this working next week to see if it works well in practice.

**Comment by jasonrhodes** [comment]
What's happening in your code example @jonambas is like the main problem with chaining things ... you use `.catch()` in `updateBillingContact` but don't re-throw, so the `.then()` in `onSubmit` will always be called. 

@jgzamora I feel like we're missing something here. Adding more flags to the reducers feels bad? I probably need to see a really rough sketch to feel it out more but IDK.

Re:
>So I wanted to keep these at the component level because there are some things that can't or shouldn't be done in the action. ie setState, history.push, form functions, ui stuff.

I'm not sure if this is a problem. We can move notifications out of the components without moving every single post-action event out of the components, like:
```js
update(values) {
  this.props.updateThing(this.props.id, values)
    .then(() => {
      this.setState();
      this.history.push();
    })
}
```

and the action creator could even be:
```js
export function updateThing(id, values) {
  return sparkpostApiRequest({
    type: 'UPDATE_THING',
    meta: {
      url: `/things/${id}`,
      data: values,
      notifications: {
        success: `Successfully updated thing ${id}`        // these could be further template-ized
        error: `There was an problem updating thing ${id}` // these could be further template-ized
      }
    }
  })
}
```

If we figure out an abstraction we all like for taking care of notifications for us so we don't have to set them up everywhere, we will still need some kind of helper that catches the errors for us whenever we _only_ care about showing a notification when a request failed. So if we need to do `.then()` and use `history.push` then it would all work, but in cases where we just want to do

```js
componentDidMount() {
  this.props.getUsersList();
}
```

We still have to handle the thrown error somehow to avoid "Unhandled promise rejection!" ... but maybe we can handle that case with something like:
```js
componentDidMount() {
  catchError(this.props.getUsersList())
}
```

**Comment by jgzamora** [comment]
The state of actions / alerts has changed significantly since this, so closing
