### ISSUE TITLE
Move Layout out of page components and into route config

### ISSUE THREAD

**Issue by jasonrhodes** [SparkPost/2web2ui#122]
To simplify render functions in the Page components, we should just specify the type of layout (app vs form) in the route config and wrap the given component in the Layout inside of our custom Route components. To do this we have to:

1. Move loading stuff out of Layout and handle that in render methods another way
1. Create a `<PublicRoute>` component that wraps given components in `<Layout>`
1. Edit `<ProtectedRoute>` to wrap in `<Layout>` similarly to how it currently wraps in `<AccessControl>`

This may be more work than it's worth right now, tbh. 🤔

**Comment by jonambas** [comment]
So I think this only moves Layout up one level (from page > route). We could move it one more level up:

<img width="603" alt="screen shot 2017-10-18 at 12 13 21 pm" src="https://user-images.githubusercontent.com/3903325/31729699-c1dc67dc-b3fd-11e7-8805-3fee3a297888.png">

**Comment by jonambas** [comment]
Being addressed in FAD-5726
