### ISSUE TITLE
Clicking outside the "select metrics" modal doesn't close it

### ISSUE THREAD

**Issue by jasonrhodes** [SparkPost/2web2ui#130]
^^

**Comment by jonambas** [comment]
None of the modals do. I think this is a matchbox problem - need to add `<WindowEvent event='click'>` with a pass through handler

**Comment by jonambas** [comment]
I believe we recently refactored modals. We should run through and test each modal to make sure both 'click outside' and 'escape' work

**Comment by jgzamora** [comment]
Looks the state of modals is currently:
- `Share` modal works perfectly
- Select Metrics modal works on esc, but not on outside click
- None of the delete modals close on click or esc
