### ISSUE TITLE
Decide what scale options should be on summary chart

### ISSUE THREAD

**Issue by jasonrhodes** [SparkPost/2web2ui#131]
Current app has linear/log/pow -- new app right now has linear/log/sqrt but that's because the "pow" type did NOT behave well. You can adjust this yourself locally and see if you can make sense of it:

https://github.com/SparkPost/2web2ui/blob/master/src/pages/reports/summary/components/ChartHeader.js#L36-L38

Add a button for any of the scale options seen here (scroll down to the "scale" block):
http://recharts.org/#/en-US/api/XAxis

What options should we show?

**Comment by ewandennis** [comment]
@ewandennis to ask TAMs for advice on which Y scaling options are useful.
