### ISSUE TITLE
Typeahead should show options on focus

### ISSUE THREAD

**Issue by jgzamora** [SparkPost/2web2ui#132]
Right now the typeahead doesn't show any results until you type. If you type something then erase, it shows you the full list. We should just show the full list as soon as the field is clicked.

**Comment by jgzamora** [comment]
Realized it shows you the options when you press the down key as well. I think it should still show you the options on click

**Comment by jasonrhodes** [comment]
Changed the title to "on focus" -- did this for the subaccount typeahead in my last ticket, we should generalize as an option for all typeaheads by creating our own generic typeahead component that wraps downshift.

**Comment by jgzamora** [comment]
@jasonrhodes solution works and should be used going forward
