### ISSUE TITLE
Follow-up Sentry configuration

### ISSUE THREAD

**Issue by bkemper** [SparkPost/2web2ui#146]
The initial integration was completed with #145.  The following is a list items we could do.

- [ ] Documentation
- [ ] Integrate with Slack
- [ ] Send state change with breadcrumbs with filters for sensitive information
- [ ] Better promise and reducer stacktraces
- [ ] ~~Relax some default filters to avoid filtered urls, etc.~~
- [ ] Configure sourcemaps to work locally
- [ ] whitelistUrls
- [ ] Ignore noise with our blacklist implementation, `ignoreErrors`, `ignoreUrls` or `whitelistUrls`, etc.
- [ ] Understand what `debug` outputs to the console
- [ ] ~~Are observables handled~~

**Comment by bkemper** [comment]
Before all users are migrated, we should evaluate if the current configuration is making it easier to track and triage production bugs.

**Comment by ewandennis** [comment]
@bkemper to cut beta, cutover and later tickets and close issue.

beta: slack integration

**Comment by bkemper** [comment]
Cut:

- [FAD-6037: Turn-off Sentry by default for local/dev environment](https://jira.int.messagesystems.com/browse/FAD-6037)
- [FAD-6039: Document Sentry for Phoenix](https://jira.int.messagesystems.com/browse/FAD-6039)
- [FAD-6041: Tweak Sentry configuration to improve triage capabilities](https://jira.int.messagesystems.com/browse/FAD-6041)
- [FAD-6038: Integrate Sentry with Slack](https://jira.int.messagesystems.com/browse/FAD-6038)
