### ISSUE TITLE
Charts date picker date formatting

### ISSUE THREAD

**Issue by jasonrhodes** [SparkPost/2web2ui#161]
Would like to see the main date range dates formatted like:
`Nov 8, 2017` or `2017-11-08` (currently they are `Nov 08, 17`)

Inside the picker, the dates at the bottom should be formatted like:
`2017-11-08` (currently they are `2017-11-8`)

**Comment by ewandennis** [comment]
Standardise on a single short and long date format, export helpers and rework existing date-presenting code.
