### ISSUE TITLE
Typeaheads should highight first item by default

### ISSUE THREAD

**Issue by jonambas** [SparkPost/2web2ui#165]
When the downshift menu opens, the first item in the list should be highlighted, so that hitting enter at that point selects the first item.

Like:
![kapture 2017-11-09 at 10 33 20](https://user-images.githubusercontent.com/3903325/32613665-8394befa-c539-11e7-9d35-be30fcb4fb56.gif)

**Comment by jasonrhodes** [comment]
This would solve a number of typeahead UX "problems" that are just slightly "off" right now

**Comment by jonambas** [comment]
Fixed as part of the ab testing epic.
