### ISSUE TITLE
Message Events Enhancements

### ISSUE THREAD

**Issue by jonambas** [SparkPost/2web2ui#167]
Some thoughts:
- ~Empty State probably needed~
- Banner (SparkPost retains message event data for 10 days.)
  - If we use the date filter component, we can try to place this somehwere in there.
  - Can also disable days in the date picker after 10 days out.
- Banner (Note: A maximum of 1,000 results displayed)
  - Jason's idea was to show "Showing x out of x results"

**Comment by bizob2828** [comment]
empty state, looks like current just shows "There are no message events for your current query", I can do that.  the other too seem out of scope of this right?

**Comment by jonambas** [comment]
@bizob2828 I was thinking about using one of the [empty state components](https://sparkpost.github.io/matchbox/?selectedKind=Empty%20State&selectedStory=Default%20Empty%20State&full=0&down=1&left=1&panelRight=0&downPanel=storybook%2Factions%2Factions-panel) we have in other places. But we shouldn't show that if results are filtered out, or if they haven't sent in 10 days.

**Comment by ewandennis** [comment]
@jonambas Fold this into the next msg events ticket and close the issue.

**Comment by jonambas** [comment]
Closed -> FAD-5911
