### ISSUE TITLE
Settle on async/await vs promises usage

### ISSUE THREAD

**Issue by jasonrhodes** [SparkPost/2web2ui#169]
Should:

- [ ] understand when we want to use one vs. another, and
- [ ] cut a JIRA ticket to refactor app for consistency
- [ ] create an ESLint rule, if possible

**Comment by rajumsys** [comment]
> understand when we want to use one vs. another, and

From top of my head, we can't use `await` for multiple promises. So promises (`.all`) will rule at least there :).

**Comment by bkemper** [comment]
@rajumsys `Promise.all` will still need to be used for multiple asynchronous requests. 

I think async/await makes writing multiple synchronous requests way easier to use and read.

```
async () => {
  const something = await getSomething();
  const result = await useSomething(something);
  ...
}
```

**Comment by jasonrhodes** [comment]
@rajumsys I think this is part of the confusion around async/await being new, because you _do_ use `await` for multiple async actions, but you still use it _with_ promises for scenarios like that.

```js
const [a, b, c] = await Promise.all([asyncA, asyncB, asyncC])
```

same with using our existing libs, which use promises:
```js
const response = await axios.get('https://someurl.com') // axios returns a promise but that's ok
```

The most annoying thing for me is try/catch mixed with block-scope, ie it makes destructuring spread get really nasty:
```js
let a, b, c

try {
  [a, b, c] = await Promise.all([getA, getB, getC])
} catch (err) {
  // handle error
}

// use a, b, c values
```

Anyway I think this is the future of JS so I do think we should start using it.
