### ISSUE TITLE
Settle on lodash vs lodash/fp usage

### ISSUE THREAD

**Issue by jasonrhodes** [SparkPost/2web2ui#170]
Should:

- [ ] Write out why/when using lodash/fp makes sense vs "regular lodash"
- [ ] Revisit need for `_.chain` syntax at all
- [ ] Add convention/explanation notes to the README.md
- [ ] Cut JIRA ticket to refactor app for consistency, if necessary
- [ ] Add ESLint rule(s), if possible

**Comment by jasonrhodes** [comment]
My personal preference here (though not fully informed I admit) is to stick to "regular lodash" and remove the fp variant, and if we find we want better immutability, we look at Immutable.js down the road. I can be swayed here but that's my initial reaction.

**Comment by bkemper** [comment]
My personal preference is to not worry about the learning curve and use `fp` to avoid a future bug.  However, this doesn't appear to be that big of a deal.  Of the 22 Lodash mutators, I could only find 5 instances -- see below.  We should also consider the native mutators, for [Array](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/prototype#Mutator_methods), Object.assign, etc.  Possibly the near term solution is to find eslint rules to not allow the use of known mutators - [eslint-plugin-prefer-object-spread](https://github.com/bryanrsmith/eslint-plugin-prefer-object-spread).

- fill
- pull
- pullAll
- pullAllBy
- pullAllWith
- pullAt
- remove
- reverse
- assign
- assignIn
- assignInWith
- assignWith
- defaults
- defaultsDeep
- merge
- mergeWith
- set
- setWith
- unset
- update
- updateWith

Use of Lodash functions
```
src/./actions/helpers/sparkpostApiRequest.js:24:      _.set(transformed, 'headers.Authorization', auth.token);
src/./config/index.js:7:const mergedConfig = _.merge({}, defaultConfig, prodConfig, maybeTestConfig);
src/./helpers/billing.js:123:    _.remove(countries, { code: 'US' }),
src/./helpers/billing.js:124:    _.remove(countries, { code: 'GB' }),
src/./helpers/billing.js:125:    _.remove(countries, { code: 'CA' }),
```

Use of `Object.assign`
```
src/./actions/bounceReport.js:24:      Object.assign(updates, getRelativeDates(updates.relativeRange) || {});
src/./actions/summaryChart.js:17:      Object.assign(updates, getRelativeDates(updates.relativeRange) || {});
src/./components/collection/Collection.js:63:      const updated = Object.assign(parsed, { page: currentPage, perPage });
src/./helpers/authCookie.js:11:  const merged = Object.assign(get() || {}, data);
src/./selectors/templates.js:5:export const cloneTemplate = (template) => Object.assign({ ...template }, { name: `${template.name} Copy`, id: `${template.id}-copy` });
```
