### ISSUE TITLE
Templates Test Data

### ISSUE THREAD

**Issue by jonambas** [SparkPost/2web2ui#173]
Currently, test data is saved on the Edit and Published pages and is used to generate the template preview and pass options to the test transmission.

As discussed today, we think:
- Saving test data on the Edit/Published pages makes it seem like they are being attached to the template, but is only really used to render and send the test transmission.
- Test Data tab should be present in the _Preview & Send_ page instead, either under a tab or next to the rendered preview.
- Preview can auto-update on a debounced onChange event on the test data editor, or through an update button.
- We can pre-populate keys in _substitution_data_ if we can figure out how to parse html

**Comment by jgzamora** [comment]
👍 My thoughts from before:
* Display the data in parallel, not in a tab
* Update button  > onChange
* Pre-population would be amazing. Sounds hard.

Note: First render of Preview/Send will always be weird/empty if they've set variables. Need to make sure it is clear what it is they should do at that point. Having it displayed and not in a tab should help, but help-text etc. would also be good

**Comment by ewandennis** [comment]
@bkemper To fold these into next templates ticket and close issue

**Comment by bkemper** [comment]
Follow progress at [FAD-6012](https://jira.int.messagesystems.com/browse/FAD-6012)
