### ISSUE TITLE
Upgrade to Eslint v4

### ISSUE THREAD

**Issue by bkemper** [SparkPost/2web2ui#174]
Version 4.0.0 was [released on June 11, 2017](https://eslint.org/blog/2017/06/eslint-v4.0.0-released).  We are [locked on v3.19.0](https://github.com/SparkPost/2web2ui/blob/8db1a3922e7190aac39c7c87d2632c02678c16ff/package.json#L58).  Before long, we should upgrade.

**Comment by ewandennis** [comment]
resolved
