### ISSUE TITLE
Message Events Details enhancements

### ISSUE THREAD

**Issue by ewandennis** [SparkPost/2web2ui#182]
The current details page shows all event fields in an alphabetised list. For readability, we could pick the "important" fields for each event type and bring them to the top of the list. Separating them from the other less commonly used fields might reduce the eye chart effect too.

As per Jon, we'll ask the TAMs to nominate a set of important fields for each event type. I expect at the following might make a good start:

 - subject
 - recipient
 - campaign
 - timestamp

Is there anything we can do to declutter this view?

**Comment by ewandennis** [comment]
@ewandennis to cut a ticket and chase down the fields we can always hide.

**Comment by jgzamora** [comment]
@ewandennis I like this idea, I'd nominate `subaccount_id` when present. I also have a few other ideas for this page:

* Localize `Refresh` loading from the `Message History` section to that panel - don't hide the entire page.
* Find a better place for the `Raw Json` section. It's currently hidden under the event details that you usually have to scroll all the way down to. In the possible use case that someone just wants to copy that JSON, it would be nice to place it somewhere more visible. I have two ideas for this:
   * Adding a `Copy Raw` action to the `Event Details` panel title, like the `Refresh` in the other panel. 
   * Make it its own panel under `Message History` and expand the text area to more lines so it's actually explorable. This panel will sometimes get pushed down to where you still have to scroll, but in any id with <15 events it would still be visible at first glance.
   * We can probably do both of these at the same time. 
* This one isn't specific to this page but I'll be making a separate issue advocating for: Promote Message Events to top level nav. 💥
