### ISSUE TITLE
DatePicker's relative range not persisted upon page reload

### ISSUE THREAD

**Issue by rajumsys** [SparkPost/2web2ui#202]
When we reload a page, the `to` and `from` re-populates correctly but the relative range is reverting to default. We should probably have date range in the query string too

<img width="1059" alt="screen shot 2017-12-06 at 4 56 14 pm" src="https://user-images.githubusercontent.com/14877079/33687621-aafeb52c-daa6-11e7-95ca-0ff369e15140.png">

**Comment by jasonrhodes** [comment]
Pulled into FAD-5924
