### ISSUE TITLE
UX Audit

### ISSUE THREAD

**Issue by jonambas** [SparkPost/2web2ui#241]
Place any UI/UX issues you find here (with screenshots if possible).

Webhooks 
- ~~Batch Status table is in a double Panel~~
- ~~Batch Status Refresh and Send Test Batch buttons can maybe panel actions~~
- ~~Update Webhook button should be in its own panel section~~
- Initial values bug on the active checkbox

API Keys
- ~~List Page needs to use `SubaccountTag`~~

Subaccounts
- List Page should use (new) Tags in the status column
  - Include with proper tooltips for compliance status
  - ie `Terminated. Please email compliance@sparkpost.com for help with your subaccount.`
- Better UX for compliance status on edit page
  - Currently just `System set statuses cannot be edited.`

Users
- Select should be sized `small`
- Delete should be a small destructive button with the label `Delete`

IP Pools
- **BUG** - going to default pool, back to the list, then to the create page - form is disabled (they share the same form name)
- Table should not be inside a panel section
- Edit, Update button should be in its own panel section
- Whats up with this help text? `Sorry, you can't edit the default pool's name. Then it wouldn't be the default!` Default maybe doesn't need its own edit page
** From JR: there'd be no way to move IPs out of the default pool if it didn't have an edit page. Might be nicer to see a list of IPs and be able to change each one's pool in addition to the list of pools, tbh

Suppressions
- List row's 'View Details' and 'Delete' buttons should be in a `Button.Group`
- Should use SubaccountTag

Support Ticket Window
- Needs a better Icon

Sending Domains
- Pending or Blocked tags next to ready for should not be inline
- Default bounce should appear first in list
- Share with all toggle should show a success alert
- After changing linked tracking domain, a second change back to the original isn't possible. Button is disabled.

---
App
- Add document page titles
- Modals should all close on escape, or when clicking outside the inner panel

MB
- ~~Radio.Group `margin-bottom` should be 0 if it is the `last-child`~~
- ~~Banners are not scaled correctly relative to other components~~

**Comment by jonambas** [comment]
`LegendItem` renders `0` at the end of the label 

![screen shot 2018-01-22 at 3 43 02 pm](https://user-images.githubusercontent.com/3903325/35243737-fcf3455a-ff8b-11e7-9a1c-61cb567d65af.png)

When not using injection time:
![screen shot 2018-01-22 at 3 42 56 pm](https://user-images.githubusercontent.com/3903325/35243738-fcfdc07a-ff8b-11e7-8d37-eeaba998701c.png)

- Replace top level metric with a banner or something else if > 100%?

**Comment by jonambas** [comment]
Subaccount Typeahead needs to accept helptext to note assignment is permanent on Template Create and Sending Domain Create

**Comment by jonambas** [comment]
Suppressions List row's 'View Details' and 'Delete' buttons should be in a `Button.Group`

**Comment by jonambas** [comment]
Billing
- The Confirmation component should remain fixed on scroll if the form overflows from the viewport
- Planpicker component dropdown height should maybe adjust based on viewport height

**Comment by jonambas** [comment]
We seem to have forgotten that `accent` is a prop available to Panel, should find appropriate places where it makes sense to add that (maybe create forms)

**Comment by jonambas** [comment]
MB Update
- Radio.Group `margin-bottom` should be 0 if it is the `last-child`

**Comment by jonambas** [comment]
Webhooks 
- Batch Status table is in a double Panel

**Comment by jonambas** [comment]
API Keys
- List Page needs to use `SubaccountTag`
- Columns widths need to be specified

**Comment by jonambas** [comment]
We should investigate all loading & errors states and try to abstract / make consistent across the board

**Comment by jonambas** [comment]
Investigate mobile UX (FAD-5941)

**Comment by jonambas** [comment]
Broken empty states

![screen shot 2018-02-09 at 9 53 57 am](https://user-images.githubusercontent.com/3903325/36033524-4f671536-0d7f-11e8-9652-3b50932210e9.png)
![screen shot 2018-02-09 at 9 54 02 am](https://user-images.githubusercontent.com/3903325/36033526-4fd3758c-0d7f-11e8-96cc-4f50e0f06cc9.png)

**Comment by jasonrhodes** [comment]
In the plain language of those metrics summary cards, should we somehow mention that the filters are also taken into account for those numbers?

<img width="989" alt="screen shot 2018-02-10 at 3 04 30 pm" src="https://user-images.githubusercontent.com/159370/36066181-ba588e16-0e73-11e8-8c3b-91cabf31f998.png">

Might be a bit misleading otherwise?

**Comment by jonambas** [comment]
Pending and ready for tags in sending domains

![screen shot 2018-02-27 at 3 54 23 pm](https://user-images.githubusercontent.com/3903325/36754273-85906954-1bd6-11e8-9fde-b039b4267359.png)

**Comment by jonambas** [comment]
Pie chart sectors with only one child shouldn't be clickable - Admin & Undetermined

<img width="672" alt="screen shot 2018-03-19 at 10 37 46 pm" src="https://user-images.githubusercontent.com/3903325/37632762-2c181bba-2bc6-11e8-8e19-2caaa07dd187.png">

**Comment by jonambas** [comment]
Closing as most of these issues have been fixed already - need to do another audit soon
