### ISSUE TITLE
Caching, Deployment and Automatic Rollback

### ISSUE THREAD

**Issue by jasonrhodes** [SparkPost/2web2ui#262]
### Requirements

1. We need to cache our static assets so that the ec2 micros aren't overwhelmed
1. We need to make sure we can easily/quickly roll back a deployment if it breaks things

### Blue Green

I think the best solution would be the "blue/green" deployment flow. In other words, we'd have a `next` symlink as a sibling to the `current` symlink, push the new code, point `next` at the newest release, then have a load balancer shift a small % of traffic to the new code and let it soak for x minutes. If errors spike, point all traffic back to `current`, if not, point the `current` symlink up to the new code and the deploy is complete.

Unfortunately, the load balancer part of this is over my head and would require Ops/Re involvement and I don't think they have time/energy for that at the moment. 

### Smoke Tests

Next best thing is probably going to be some small set of browser based tests, whether we use Selenium or some newer tool and run them against the live-running app. I am not super excited about this method because of how hard it is to get those kinds of tests to be stable/reliable for something like deployment, but we'll make do for now.

#### How to smoke test/rollback

The current UI has a hostname that's just not cloudfront cached, so the flow is:

1. Push new code
1. Run tests against the uncached hostname
1. If tests pass, we force-invalidate the cache
1. If tests fail, we push the old code back into place and don't invalidate

Problem is, things can fall out of cache at any time with Cloudfront, so if something falls out of the cache for a user while we are verifying, they get new code suddenly and are possibly in a bad state.

Alternatively, we could incorporate the `next` symlink idea into our deployment flow and point a hostname like `next.app.sparkpost.com` at that nginx block. Then we can run tests against the next hostname just like we do now, but if Cloudfront things fall out of cache, they still get the old code.

Once tests pass, we flip the symlink and invalidate the cache.

#### What tool to use for tests

:BIG SHRUG EMOTICON:

**Comment by bizob2828** [comment]
In theory this all sounds great but we'd probably need a strategy to phase it in.  It seems like ultimate goal would be the initial approach you pitched with % traffic on next vs current.  

I wouldn't worry about cache fall out. I'd ask @ischer how we spec'd this in the existing UI.  We could set the flag that sync angular and just continue to use protractor until we have a better solution: http://www.joelotter.com/2015/04/18/protractor-reactjs.html

**Comment by jasonrhodes** [comment]
I do worry about cache fall out because I think we had an outage that was related to that. I also think it's easy to fix and may actually make our deploys even simpler (might not need to do an invalidation at all).

**Comment by jasonrhodes** [comment]
I'll look at nightwatch too.

**Comment by jasonrhodes** [comment]
Ian expressed some concern that even with just the config uncached, the ec2 micro could get overwhelmed in extreme situations. We probably don't have to do this right away for beta, but config caching idea I had:

Change nginx rewrite from `/assets/tenant/(.*)` to `/config/tenant/(somePattern)(.*)` and replace `somePattern` with the webui hostname, so we can "rev fingerprint" the reference to the file (and get CF/browser caching for it) without having to change the filename. Each deploy will cause a new cache miss.

Thing to think through: rollback would mean the "old" config would still be in cache, maybe, but if it fell out of cache you'd get new config with old code, so config would really really need to be BC to prevent bad situations.

Other solution would be to start putting the generated config inside of the releases folder so config is tied to a release, and rollback would actually be "complete".
