### ISSUE TITLE
Action failure case bugs

### ISSUE THREAD

**Issue by jonambas** [SparkPost/2web2ui#347]
- Billing - failure on get plans & countries should maybe redirect back
- Dashboard - if account request fails, usage report loads forever
- Message events list - clicking 'Try again' in the ApiErrorBanner results in a `TypeError`
- Message events details - documentation call failure (for tooltips) is a candidate for a silent flag
- Message events details - getMessageHistory (single page get) failure should redirect back to list
- Ip Pools details - if the get single call fails, error banner is show, but should hide the surrounding Page component, or redirect to list
- Profile Page - tfa, errors need rework (see comment below)
- Recipient List - if the get single call fails, the following history push is not called, loads forever
- Recipient List create - if fails when communicating with API, no error message is displayed
- Sending domain details - get failure shows loading forever
- Subaccount details - get failure should redirect back to list
- Subaccount details - api keys and sending domain list should maybe show an error state
- Webhooks test tab - if samples call fails, loads forever

IP pool, Templates, Tracking Domains, Recipient, Subaccount and Sending Domain lists - empty state tests should check !error

**Comment by jonambas** [comment]
TfaManager needs a rework
- if you open the enable modal and getSecret fails, alert is shown but UI shows loading forever (should maybe close the modal)
- if getTfaStatus fails, panel shows loading forever
- if getTfaBackupStatus fails, panel shows 0 backup codes 
- BackupCodesModal form shows 'Incorrect Password' as a validation error if generate backup code request fails
- if disable tfa fails, form shows 'Incorrect Password' as a validation error

**Comment by bkemper** [comment]
Summary page - there is a potential for multiple error alerts with the same message.
