### ISSUE TITLE
Fix "last hour" x-axis for summary chart

### ISSUE THREAD

**Issue by jasonrhodes** [SparkPost/2web2ui#49]
Angular app "last hour" x-axis:

![screen shot 2017-08-23 at 2 49 50 pm](https://user-images.githubusercontent.com/159370/29741909-c5b479d2-8a43-11e7-9555-f1e72f30c4a4.png)

Phoenix app "last hour" x-axis:

<img width="872" alt="screen shot 2017-08-26 at 9 38 01 am" src="https://user-images.githubusercontent.com/159370/29741911-cf1969d8-8a43-11e7-9e8e-29d029ac0d2f.png">

**Comment by jonambas** [comment]
Not sure we can force every 15 minutes. We can set `interval` manually in `<XAxis/>` to every 15 ticks, but I don't think there's a way to force it to end on 00, 15, 30, 45
