### ISSUE TITLE
Caching issues after deploy

### ISSUE THREAD

**Issue by jasonrhodes** [SparkPost/2web2ui#52]
Often needs a hard refresh to not have a blank page, I think because the index.html file is cached and therefore is looking for the old JS bundle, but that bundle file isn't cached so it fails.

Maybe adding this to the index.html `<head>` would work, but there might be a "better" way:

```
<meta http-equiv="Cache-control" content="no-cache, no-store, must-revalidate">
```

**Comment by jasonrhodes** [comment]
More clues on this...

If I go to our uncached staging URL for the angular app, I see this in the headers:
<img width="683" alt="screen shot 2017-08-26 at 5 05 26 pm" src="https://user-images.githubusercontent.com/159370/29745098-d2a04f44-8a80-11e7-9b08-fdfcd646d658.png">

But in this app, I see this:
<img width="796" alt="screen shot 2017-08-26 at 5 06 12 pm" src="https://user-images.githubusercontent.com/159370/29745103-e65d7052-8a80-11e7-81a5-1fbd50de5d6c.png">

So how does the browser no to include cache-control: no-cache in our angular app? I don't see that meta tag described above appearing in our angular index.html ... how do internets work

**Comment by jamesashby** [comment]
@jasonrhodes can you close this; as discussed in today's standup?

**Comment by jasonrhodes** [comment]
Fixed by:
* Turning off service worker (we don't think it's useful to our app)
* Split out code for the GIANT editor lib, so we could in theory turn SW back on and avoid this problem (but we decided not to anyway)
