### ISSUE TITLE
Summary chart time mode toggle

### ISSUE THREAD

**Issue by jasonrhodes** [SparkPost/2web2ui#53]
Right now it's a button that says "Event Time", that when you click it switches to "Injection Time" ... we agreed this would work well as a toggle similar to "Log|Power" toggles already there. 

Related: I think we should use "Real Time" instead of "Event Time" ... or something else because "Event Time" isn't currently used as far as I know and to me it sounds pretty confusing. We can involve product, Brent, etc. on this one.

**Comment by jonambas** [comment]
Switched to a "Real Time" and "Injection Time" button group in #57
