### ISSUE TITLE
Recharts - log scale doesnt render 0 values

### ISSUE THREAD

**Issue by jonambas** [SparkPost/2web2ui#68]
Because log(0) is not a number, recharts breaks when trying to make the svg line
```
Error: <path> attribute d: Expected number, "….67,InfinityL249.583…".
```
Current UI renders these points at 0 anyway

![screen shot 2017-09-01 at 3 26 13 pm](https://user-images.githubusercontent.com/3903325/29984785-eb29b6a6-8f29-11e7-9204-58721971c543.png)

Found in #66

**Comment by bizob2828** [comment]
Logged in jira, closing this
